---
- hosts: all

  become: yes

  tasks:
    - name: install basic packages
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      loop:
        - vim
        - telnet
        - git
        - wget
